# Generated by Django 5.1.4 on 2024-12-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=20)),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('tempo_jogado', models.IntegerField()),
                ('img_icon_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('steam_id', 'appid')},
            },
        ),
    ]
