# Generated by Django 5.1.4 on 2024-12-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_rename_name_game_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='nome',
            new_name='name',
        ),
    ]
